# Generated by Django 4.2.8 on 2025-03-13 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trigger_type', models.CharField(choices=[('scheduled', 'Scheduled'), ('api', 'API')], max_length=10)),
                ('schedule_time', models.DateTimeField(blank=True, null=True)),
                ('interval', models.PositiveIntegerField(blank=True, null=True)),
                ('api_payload', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('is_manual_test', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_trigger_app.trigger')),
            ],
        ),
    ]
